---
version: 2
  jobs:
    build:
      working_directory: ~/red_timer
      docker: 
        - image: circleci/ruby:2.6.3
        environment:
          RAILS_ENV: test
        - image: postgres:9.5
          environment:
            POSTGRES_USER: red_timer
            POSTGRES_DB: red_timer_test
            POSTGRES_PASSWORD: ""
    steps:
      - checkout
      # Restore cached dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: your-app-name-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: your-app-name-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Setup the test environment
      - run: cp .sample.env .env
      # Setup the database
      - run: bundle exec rake db:setup
      # Run the tests
      - run: bundle exec rake

